## RandomSpawnpoint Config

# Maximum distance the player can be spawned from the origin. Must be a positive integer.
# Default: 5000
SpawnDistance: 5000

# Don't spawn the player on or in these blocks.
BlockBlacklist:
  - LAVA
  - FIRE
  - WATER
  - POWDER_SNOW
  - MAGMA_BLOCK
  - SWEET_BERRY_BUSH
  - CAMPFIRE
  - SOUL_CAMPFIRE

# Sets the player's compass location to their unique world spawn.
# Default: true
SetPlayerCompassLocation: true