##RandomSpawnpoint Config

#Max distance the player can be spawned from the origin. Must be a positive integer.
SpawnDistance: 5000

#Don't spawn the player on or in these blocks
BlockBlacklist:
  - LAVA
  - FIRE
  - WATER
  - POWDER_SNOW
  - MAGMA_BLOCK
  - SWEET_BERRY_BUSH
  - CAMPFIRE
  - SOUL_CAMPFIRE