name: RandomSpawnpoint
version: '${project.version}'
main: dev.michaud.greenpanda.randomspawnpoint.RandomSpawnpoint
api-version: 1.19
authors: [ PandaDev ]
description: When players spawn the first time, their spawnpoint will be random.
commands:
  setrandomspawnpoint:
    description: Sets your spawnpoint to a random location.
    permission: randomspawnpoint.setspawn
permissions:
  randomspawnpoint.setspawn:
    description: Lets you set your spawnpoint to a random location.
    default: op