name: RandomSpawnpoint
version: '${project.version}'
main: me.greenpanda.randomspawnpoint.RandomSpawnpoint
api-version: 1.18
description: When players spawn in the world, there spawnpoint will be a random place within a configurable distance.
commands:
  setrandomspawnpoint:
    description: Sets your spawn point to a random location.
    aliases:
      - rspawnpoint